# Generated by Django 3.2.23 on 2024-02-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostModel',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cost', models.FloatField(default=0.0)),
            ],
        ),
    ]
